--- @type lsp.CompletionItem[]
local entries = {}
local M = {}

-- strips YAML comments from a line
-- Preserves # inside quotes otherwise strips content after #
local function strip_yaml_comment(str)
  if not str then
    return nil
  end
  local quoted = str:match '^%s*(".-")' or str:match "^%s*('.-')"
  if quoted then
    return quoted
  end
  return str:match '^%s*(.-)%s*#' or str:match '^%s*(.-)%s*$'
end

-- TODO: Won't handle a table of bibs but that feels very niche/edge case
--- Locates the bibliography reference in buffer or _quarto.yml
--- @param lines table The lines of the current buffer to parse
--- @return string|nil bib_str An unsanitized bibliography path string (YAML comments stripped)
--- @return string|nil root The path to root of the file where the bibliography is referenced.
local function locate_bib_str(lines)
  local root = vim.fn.expand '%:p:h'
  for _, line in ipairs(lines) do
    local bib_line = string.match(line, [[bibliography[%s]*[:=\(]%s*(.-)%s*[\)]?$]])
    local location = strip_yaml_comment(bib_line)
    if location and location ~= '' then
      return location, root
    end
  end
  -- no bib locally defined
  -- test for quarto project-wide definition
  local fname = vim.api.nvim_buf_get_name(0)
  if vim.fn.has 'nvim-10.0.0' then
    root = vim.fs.root(fname, '_quarto.yml')
  else
    root = require('lspconfig.util').root_pattern '_quarto.yml'(fname)
  end
  if root then
    local file = root .. '/_quarto.yml'
    local quarto_lines
    local ok, lines_or_err = pcall(io.lines, file)
    if ok then
      quarto_lines = lines_or_err
    else
      vim.notify_once(
        string.format('Unable to open _quarto_yml file at %s:%s', file, lines_or_err),
        vim.log.levels.WARN
      )
      return nil
    end
    for line in quarto_lines do
      local bib_line = string.match(line, 'bibliography:%s*(.+)$')
      local location = strip_yaml_comment(bib_line)
      if location then
        return location, root
      end
    end
  end
end

-- Clean up the path from a bibliography string
local function sanitize_path(path)
  -- Trim whitespace
  path = path:match '^%s*(.-)%s*$'
  -- Remove surrounding quotes
  local unquoted = path:match '^"(.-)"$' or path:match "^'(.-)'$" or path
  -- Unescape
  unquoted = unquoted:gsub('\\ ', ' ')
  unquoted = unquoted:gsub('\\([/"])', '%1')
  return unquoted
end

--- Resolves bibliography file path from string or function
--- @param lines table The lines of the current buffer to parse
--- @return string|nil Absolute path to bibliography file or nil if not found
local function get_bib_path(lines)
  -- locate string of bib path (YAML frontmatter or _quarto.yml)
  local bib_str, root = locate_bib_str(lines)
  if not bib_str then
    vim.notify_once('cmp-pandoc-references: No bibliography file specification found in document', vim.log.levels.DEBUG)
    return nil
  end

  local sanitized_path = sanitize_path(bib_str)
  -- Try direct path first
  local direct_path = vim.fn.expand(sanitized_path)
  if vim.fn.filereadable(direct_path) == 1 then
    return vim.fn.fnamemodify(direct_path, ':p')
  end
  -- Try relative to root (_quarto.yml or buf)
  local full_path = root .. '/' .. sanitized_path
  full_path = vim.fn.expand(full_path)
  if vim.fn.filereadable(full_path) == 1 then
    return vim.fn.fnamemodify(full_path, ':p')
  end
  -- If we get here, no readable file was found
  vim.notify_once(
    string.format('cmp-pandoc-references: Bibliography file not found. Tried:\n- %s\n- %s', direct_path, full_path),
    vim.log.levels.DEBUG
  )
  return nil
end

-- Remove newline & excessive whitespace
local function clean(text)
  if text then
    text = text:gsub('\n', ' ')
    return text:gsub('%s%s+', ' ')
  else
    return text
  end
end

-- Parses the .bib file, formatting the completion item
-- Adapted from http://rgieseke.github.io/ta-bibtex/
local function parse_bib(filename, fields)
  local file, err = io.open(filename, 'rb')
  if file == nil then
    vim.notify_once(string.format('Unable to open bibliography file at %s:%s', filename, err), vim.log.levels.WARN)
    return
  end
  local bibentries = file:read '*all'
  file:close()
  for bibentry in bibentries:gmatch '@.-\n}\n' do
    local title = clean(bibentry:match 'title%s*=%s*["{]*(.-)["}],?') or ''
    local author = clean(bibentry:match 'author%s*=%s*["{]*(.-)["}],?') or ''
    local year = bibentry:match 'year%s*=%s*["{]?(%d+)["}]?,?' or ''

    -- Skip comments generated by jabref, go to end of loop
    if bibentry:match '@[Cc]omment{(.-),' then
      goto continue
    end

    local doc = { '**' .. title .. '**', '', '*' .. author .. '*', year }

    --- @type lsp.CompletionItem
    local entry = {
      label = '@' .. bibentry:match '@%w+{(.-),',
      kind = fields.entry_kind,
      insertTextFormat = vim.lsp.protocol.InsertTextFormat.PlainText,
      documentation = {
        kind = fields.documentation_kind,
        value = table.concat(doc, '\n'),
      },
    }

    table.insert(entries, entry)
    ::continue::
  end
end

-- Parses the references in the current file, formatting for completion
local function parse_ref(lines, fields)
  local words = table.concat(lines, '\n')

  for ref in words:gmatch '{#(%a+[:%-][%w_-]+)' do
    local entry = {}
    entry.label = '@' .. ref
    entry.kind = fields.entry_kind
    table.insert(entries, entry)
  end
  for ref in words:gmatch '#| label: (%a+[:%-][%w_-]+)' do
    local entry = {}
    entry.label = '@' .. ref
    entry.kind = fields.entry_kind
    table.insert(entries, entry)
  end
end

-- Returns the entries as a table, clearing entries beforehand
function M.get_entries(lines, fields)
  local location = get_bib_path(lines)

  entries = {}

  if location and vim.fn.filereadable(location) == 1 then
    parse_bib(location, fields)
  end
  parse_ref(lines, fields)

  return entries
end

return M
